# Generated by Django 2.0.10 on 2019-01-20 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.IntegerField()),
                ('luc', models.IntegerField()),
                ('razaoSocial', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Triangulacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendaInformadaLojista', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vendaReducaoz', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vendaAuditoriaPresencial', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data', models.DateTimeField()),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venda.Loja')),
            ],
        ),
        migrations.AddField(
            model_name='auditor',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venda.Loja'),
        ),
        migrations.AddField(
            model_name='auditor',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
