# Generated by Django 2.0.10 on 2019-01-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_auto_20190120_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditor',
            name='loja',
        ),
        migrations.AddField(
            model_name='auditor',
            name='loja',
            field=models.ManyToManyField(to='venda.Loja'),
        ),
    ]
